services:
  - type: web
    name: seantechdesk-web
    env: node
    plan: free
    buildCommand: |
      set -e
      echo "== STRIP BOMs (server/client/schema) =="
      perl -i -pe 's/^\x{FEFF}//' server/package.json || true
      perl -i -pe 's/^\x{FEFF}//' client/package.json || true
      perl -i -pe 's/^\x{FEFF}//' server/prisma/schema.prisma || true

      echo "== INSTALL + BUILD CLIENT =="
      npm install --prefix client
      npm run build --prefix client

      echo "== INSTALL SERVER =="
      npm install --prefix server

      echo "== PRISMA GENERATE + DEPLOY =="
      cd server && npx prisma generate
      cd server && npx prisma migrate deploy
    startCommand: node server/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: seantechdesk-db
          property: connectionString
    healthCheckPath: /api/health
databases:
  - name: seantechdesk-db
    plan: free