services:
  - type: web
    name: seantechdesk-web
    env: node
    plan: free
    buildCommand: |
      (npm ci --prefix client) || (npm install --prefix client)
      npm run build --prefix client
      (npm ci --prefix server) || (npm install --prefix server)
      cd server && npx prisma migrate deploy
    startCommand: node server/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: seantechdesk-db
          property: connectionString
    healthCheckPath: /api/health
databases:
  - name: seantechdesk-db
    plan: free