services:
  - type: web
    name: seantechdesk-web
    env: node
    plan: free
    buildCommand: |
      set -e

      echo "== STRIP BOMs with Node =="
      node -e "const fs=require('fs');const files=['server/package.json','client/package.json','server/prisma/schema.prisma'];files.forEach(f=>{if(fs.existsSync(f)){let s=fs.readFileSync(f,'utf8');if(s.charCodeAt(0)===0xFEFF){s=s.slice(1);}fs.writeFileSync(f,s)}})"

      echo "== INSTALL + BUILD CLIENT =="
      npm install --prefix client
      npm run build --prefix client

      echo "== INSTALL SERVER =="
      npm install --prefix server

      echo '== SHOW server/package.json first 40 chars (sanity) =='
      node -e "process.stdout.write(require('fs').readFileSync('server/package.json','utf8').slice(0,40))"

      echo "== PRISMA GENERATE + DEPLOY =="
      cd server && npx prisma generate
      cd server && npx prisma migrate deploy
    startCommand: node server/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: seantechdesk-db
          property: connectionString
    healthCheckPath: /api/health
databases:
  - name: seantechdesk-db
    plan: free